server:
  servlet:
    encoding:
      charset: UTF-8
      enable: true
      force: true
  shutdown: graceful

spring:
  profiles:
    active: ${PROFILE}
  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  charset:
    console: UTF-8
    file: UTF-8
  level:
    root: info

---

server:
  port: 8081

spring:
  config:
    activate:
      on-profile: deploy
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gostop
    username: root
    password: 1

  data:
    redis:
      host: localhost
      port: 6379